site_name: UbuCon Asia Organizer guide
site_name_short: UCA Organizer guide
site_url: http://www.ubucon.asia/
site_base_url: /organizer-guide/
site_description: Detailed documentation and guidance on organizing UbuCon Asia event.
site_author: UbuCon Asia Organizing team

repo_url: https://github.com/ubucon-asia/organizer-guide
repo_name: ubucon-asia/organizer-guide
contact_email: contact@ubuntu.com
copyright: Copyright &copy; 2023-Present UbuCon Asia Organizing team (contact at ubucon.asia)

theme:
    name: ubuntu

nav:
    - Home:
      - index.md
      - overview.md
      - teams_roles.md

plugins:
    - search